
# NLP Feature Engineering - Dataset Santé Mentale

Ce notebook applique sur **ton dataset réel** :

1. NLP Pipeline  
2. Bag of Words  
3. TF-IDF  
4. Average Word Embedding  

But : comprendre concrètement comment transformer du texte en variables numériques avant le Machine Learning.

In [4]:

import pandas as pd

# Modifier si nécessaire
df = pd.read_csv(r"C:\Users\lenovo\Downloads\data (2).csv")
df.head()

   Unnamed: 0                                          statement   status
0           0                                         oh my gosh  Anxiety
1           1  trouble sleeping, confused mind, restless hear...  Anxiety
2           2  All wrong, back off dear, forward doubt. Stay ...  Anxiety
3           3  I've shifted my focus to something else but I'...  Anxiety
4           4  I'm restless and restless, it's been a month n...  Anxiety


Le dataset contient :

- `statement` → texte
- `status` → label

On va maintenant appliquer chaque méthode sur tes vraies données.

## 1. NLP Pipeline

In [5]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# télécharger toutes les ressources nécessaires
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    
    # supprimer urls
    text = re.sub(r"http\S+", "", text)
    
    # supprimer caractères spéciaux
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    
    # tokenization
    tokens = word_tokenize(text)
    
    # supprimer stopwords
    tokens = [word for word in tokens if word not in stop_words]
    
    return tokens

print("Texte original :")
print(df['statement'][0])

print("\nTexte après nettoyage :")
print(clean_text(df['statement'][0]))

Texte original :
oh my gosh

Texte après nettoyage :
['oh', 'gosh']

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Ici on prépare les données :

- suppression ponctuation
- suppression stopwords
- tokenisation

Le texte devient plus propre avant l'entraînement.

## 2. Bag of Words

In [6]:

from sklearn.feature_extraction.text import CountVectorizer

sample=df['statement'].head(5)

vectorizer=CountVectorizer()
X=vectorizer.fit_transform(sample)

import pandas as pd
bow_df=pd.DataFrame(
    X.toarray(),
    columns=vectorizer.get_feature_names_out()
)

bow_df

,all,and,back,been,boy,but,confused,dear,do,doubt,...,stay,still,to,trouble,tune,ve,what,worried,wrong,you
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,1,0,0,0,...,0,0,0,1,1,0,0,0,0,0
2,1,1,1,0,0,0,0,1,0,1,...,1,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,1,0,0,0,0,...,0,1,1,0,0,1,0,1,0,0
4,0,1,0,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1


Bag of Words compte simplement les mots.

Si "anxiety" apparaît souvent dans les textes Anxiety → le modèle apprend ce pattern.

## 3. TF-IDF

In [8]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

X_tfidf=tfidf.fit_transform(sample)

tfidf_df=pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

,all,and,back,been,boy,but,confused,dear,do,doubt,...,stay,still,to,trouble,tune,ve,what,worried,wrong,you
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.267458,0.000000,0.000000,0.000000,0.000000,0.000000,0.331507,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.331507,0.331507,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.231976,0.231976,0.287529,0.000000,0.000000,0.000000,0.000000,0.287529,0.000000,0.287529,...,0.287529,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.287529,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.321896,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.321896,0.321896,0.000000,0.000000,0.321896,0.000000,0.321896,0.000000,0.000000
4,0.000000,0.238482,0.000000,0.295592,0.295592,0.000000,0.000000,0.000000,0.295592,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.295592,0.000000,0.000000,0.295592


TF-IDF donne plus d’importance aux mots rares mais importants.

Exemple :

- "the" → faible poids
- "suicide" → poids élevé

Très utile pour ton dataset.

## 4. Average Word Embedding

In [10]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gensim) (2.3.4)
Requirement already satisfied: scipy>=1.7.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from gensim) (1.16.3)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.6.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: wrapt in c:\users\lenovo\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)
Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
    --------------------------------------- 0.5/24.4 MB 320.5 kB/s eta 0:01:15
    --------------------------------------- 0.5/24.4 MB 320.5 kB/s eta 0:01:15
    --------------------------------------- 0.5/24.4 MB 320.5 kB/s eta 0:01:15
   - -------------------------------------- 0.8/24.4 MB 375.5 kB/s eta 0:01:03
   - -------------------------------------- 0.8/24.4 MB 375.5 kB/s eta 0:01:03
   - -------------------------------------- 0.8/24.4 MB 375.5 kB/s eta 0:01:03
   - -------------------------------------- 1.0/24.4 MB 407.2 kB/s eta 0:00:58
   - -------------------------------------- 1.0/24.4 MB 407.2 kB/s eta 0:00:58
   - -------------------------------------- 1.0/24.4 MB 407.2 kB/s eta 0:00:58
   -- ------------------------------------- 1.3/24.4 MB 393.5 kB/s eta 0:00:59
   -- ------------------------------------- 1.3/24.4 MB 393.5 kB/s eta 0:00:59
   -- ------------------------------------- 1.3/24.4 MB 393.5 kB/s eta 0:00:59
   -- ------------------------------------- 1.6/24.4 MB 406.0 kB/s eta 0:00:57
   -- ------------------------------------- 1.6/24.4 MB 406.0 kB/s eta 0:00:57
   -- ------------------------------------- 1.6/24.4 MB 406.0 kB/s eta 0:00:57
   --- ------------------------------------ 1.8/24.4 MB 389.9 kB/s eta 0:00:58
   --- ------------------------------------ 1.8/24.4 MB 389.9 kB/s eta 0:00:58
   --- ------------------------------------ 1.8/24.4 MB 389.9 kB/s eta 0:00:58
   --- ------------------------------------ 1.8/24.4 MB 389.9 kB/s eta 0:00:58
   --- ------------------------------------ 2.1/24.4 MB 374.6 kB/s eta 0:01:00
   --- ------------------------------------ 2.1/24.4 MB 374.6 kB/s eta 0:01:00
   --- ------------------------------------ 2.1/24.4 MB 374.6 kB/s eta 0:01:00
   --- ------------------------------------ 2.1/24.4 MB 374.6 kB/s eta 0:01:00
   --- ------------------------------------ 2.4/24.4 MB 372.9 kB/s eta 0:01:00
   --- ------------------------------------ 2.4/24.4 MB 372.9 kB/s eta 0:01:00
   --- ------------------------------------ 2.4/24.4 MB 372.9 kB/s eta 0:01:00
   ---- ----------------------------------- 2.6/24.4 MB 374.5 kB/s eta 0:00:59
   ---- ----------------------------------- 2.6/24.4 MB 374.5 kB/s eta 0:00:59
   ---- ----------------------------------- 2.6/24.4 MB 374.5 kB/s eta 0:00:59
   ---- ----------------------------------- 2.9/24.4 MB 381.9 kB/s eta 0:00:57
   ---- ----------------------------------- 2.9/24.4 MB 381.9 kB/s eta 0:00:57
   ---- ----------------------------------- 2.9/24.4 MB 381.9 kB/s eta 0:00:57
   ----- ---------------------------------- 3.1/24.4 MB 384.6 kB/s eta 0:00:56
   ----- ---------------------------------- 3.4/24.4 MB 400.9 kB/s eta 0:00:53
   ------ --------------------------------- 3.7/24.4 MB 423.9 kB/s eta 0:00:49
   ------ --------------------------------- 3.7/24.4 MB 423.9 kB/s eta 0:00:49
   ------ --------------------------------- 3.9/24.4 MB 434.5 kB/s eta 0:00:48
   ------ --------------------------------- 3.9/24.4 MB 434.5 kB/s eta 0:00:48
   ------ --------------------------------- 4.2/24.4 MB 439.7 kB/s eta 0:00:46
   ------ --------------------------------- 4.2/24.4 MB 439.7 kB/s eta 0:00:46
   ------- -------------------------------- 4.5/24.4 MB 448.4 kB/s eta 0:00:45
   ------- -------------------------------- 4.5/24.4 MB 448.4 kB/s eta 0:00:45
   ------- -------------------------------- 4.5/24.4 MB 448.4 kB/s eta 0:00:45
   ------- -------------------------------- 4.5/24.4 MB 448.4 kB/s eta 0:00:45
   ------- -------------------------------- 4.7/24.4 MB 441.8 kB/s eta 0:00:45
   ------- -------------------------------- 4.7/24.4 MB 441.8 kB/s eta 0:00:45
   -------- ------------------------------- 5.0/24.4 MB 442.1 kB/s eta 0:00:44
   -------- ------------------------------- 5.0/24.4 MB 442.1 kB/s eta 0:00:44
   -------- ------------------------------- 5.0/24.4 MB 442.1 kB/s eta 0:00:44
   -------- ------------------------------- 5.2/24.4 MB 445.2 kB/s eta 0:00:44
   --------- ------------------------------ 5.5/24.4 MB 457.5 kB/s eta 0:00:42
   --------- ------------------------------ 5.8/24.4 MB 470.2 kB/s eta 0:00:40
   --------- ------------------------------ 5.8/24.4 MB 470.2 kB/s eta 0:00:40
   --------- ------------------------------ 6.0/24.4 MB 478.4 kB/s eta 0:00:39
   --------- ------------------------------ 6.0/24.4 MB 478.4 kB/s eta 0:00:39
   ---------- ----------------------------- 6.6/24.4 MB 500.6 kB/s eta 0:00:36
   ---------- ----------------------------- 6.6/24.4 MB 500.6 kB/s eta 0:00:36
   ----------- ---------------------------- 6.8/24.4 MB 511.0 kB/s eta 0:00:35
   ----------- ---------------------------- 7.1/24.4 MB 522.6 kB/s eta 0:00:34
   ----------- ---------------------------- 7.1/24.4 MB 522.6 kB/s eta 0:00:34
   ------------ --------------------------- 7.3/24.4 MB 522.6 kB/s eta 0:00:33
   ------------ --------------------------- 7.6/24.4 MB 531.1 kB/s eta 0:00:32
   ------------ --------------------------- 7.6/24.4 MB 531.1 kB/s eta 0:00:32
   ------------ --------------------------- 7.9/24.4 MB 532.4 kB/s eta 0:00:32
   ------------ --------------------------- 7.9/24.4 MB 532.4 kB/s eta 0:00:32
   ------------ --------------------------- 7.9/24.4 MB 532.4 kB/s eta 0:00:32
   ------------ --------------------------- 7.9/24.4 MB 532.4 kB/s eta 0:00:32
   ------------ --------------------------- 7.9/24.4 MB 532.4 kB/s eta 0:00:32
   ------------- -------------------------- 8.1/24.4 MB 516.4 kB/s eta 0:00:32
   ------------- -------------------------- 8.1/24.4 MB 516.4 kB/s eta 0:00:32
   ------------- -------------------------- 8.1/24.4 MB 516.4 kB/s eta 0:00:32
   ------------- -------------------------- 8.1/24.4 MB 516.4 kB/s eta 0:00:32
   ------------- -------------------------- 8.4/24.4 MB 506.6 kB/s eta 0:00:32
   ------------- -------------------------- 8.4/24.4 MB 506.6 kB/s eta 0:00:32
   ------------- -------------------------- 8.4/24.4 MB 506.6 kB/s eta 0:00:32
   -------------- ------------------------- 8.7/24.4 MB 504.1 kB/s eta 0:00:32
   -------------- ------------------------- 8.7/24.4 MB 504.1 kB/s eta 0:00:32
   -------------- ------------------------- 8.9/24.4 MB 502.5 kB/s eta 0:00:31
   -------------- ------------------------- 8.9/24.4 MB 502.5 kB/s eta 0:00:31
   -------------- ------------------------- 8.9/24.4 MB 502.5 kB/s eta 0:00:31
   --------------- ------------------------ 9.2/24.4 MB 502.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.2/24.4 MB 502.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.2/24.4 MB 502.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.2/24.4 MB 502.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.4/24.4 MB 492.8 kB/s eta 0:00:31
   --------------- ------------------------ 9.4/24.4 MB 492.8 kB/s eta 0:00:31
   --------------- ------------------------ 9.4/24.4 MB 492.8 kB/s eta 0:00:31
   --------------- ------------------------ 9.7/24.4 MB 487.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.7/24.4 MB 487.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.7/24.4 MB 487.0 kB/s eta 0:00:31
   --------------- ------------------------ 9.7/24.4 MB 487.0 kB/s eta 0:00:31
   ---------------- ----------------------- 10.0/24.4 MB 480.8 kB/s eta 0:00:31
   ---------------- ----------------------- 10.0/24.4 MB 480.8 kB/s eta 0:00:31
   ---------------- ----------------------- 10.0/24.4 MB 480.8 kB/s eta 0:00:31
   ---------------- ----------------------- 10.2/24.4 MB 478.7 kB/s eta 0:00:30
   ---------------- ----------------------- 10.2/24.4 MB 478.7 kB/s eta 0:00:30
   ---------------- ----------------------- 10.2/24.4 MB 478.7 kB/s eta 0:00:30
   ----------------- ---------------------- 10.5/24.4 MB 476.8 kB/s eta 0:00:30
   ----------------- ---------------------- 10.5/24.4 MB 476.8 kB/s eta 0:00:30
   ----------------- ---------------------- 10.5/24.4 MB 476.8 kB/s eta 0:00:30
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ----------------- ---------------------- 10.7/24.4 MB 473.4 kB/s eta 0:00:29
   ------------------ --------------------- 11.3/24.4 MB 460.7 kB/s eta 0:00:29
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------ --------------------- 11.5/24.4 MB 467.5 kB/s eta 0:00:28
   ------------------- -------------------- 11.8/24.4 MB 453.2 kB/s eta 0:00:28
   ------------------- -------------------- 12.1/24.4 MB 457.3 kB/s eta 0:00:27
   ------------------- -------------------- 12.1/24.4 MB 457.3 kB/s eta 0:00:27
   ------------------- -------------------- 12.1/24.4 MB 457.3 kB/s eta 0:00:27
   -------------------- ------------------- 12.3/24.4 MB 456.0 kB/s eta 0:00:27
   -------------------- ------------------- 12.3/24.4 MB 456.0 kB/s eta 0:00:27
   -------------------- ------------------- 12.6/24.4 MB 459.7 kB/s eta 0:00:26
   -------------------- ------------------- 12.6/24.4 MB 459.7 kB/s eta 0:00:26
   -------------------- ------------------- 12.6/24.4 MB 459.7 kB/s eta 0:00:26
   --------------------- ------------------ 12.8/24.4 MB 458.4 kB/s eta 0:00:26
   --------------------- ------------------ 12.8/24.4 MB 458.4 kB/s eta 0:00:26
   --------------------- ------------------ 12.8/24.4 MB 458.4 kB/s eta 0:00:26
   --------------------- ------------------ 12.8/24.4 MB 458.4 kB/s eta 0:00:26
   --------------------- ------------------ 13.1/24.4 MB 453.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.1/24.4 MB 453.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.1/24.4 MB 453.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.1/24.4 MB 453.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.4/24.4 MB 449.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.4/24.4 MB 449.0 kB/s eta 0:00:25
   --------------------- ------------------ 13.4/24.4 MB 449.0 kB/s eta 0:00:25
   ---------------------- ----------------- 13.6/24.4 MB 449.0 kB/s eta 0:00:24
   ---------------------- ----------------- 13.6/24.4 MB 449.0 kB/s eta 0:00:24
   ---------------------- ----------------- 13.6/24.4 MB 449.0 kB/s eta 0:00:24
   ---------------------- ----------------- 13.9/24.4 MB 451.4 kB/s eta 0:00:24
   ---------------------- ----------------- 13.9/24.4 MB 451.4 kB/s eta 0:00:24
   ---------------------- ----------------- 13.9/24.4 MB 451.4 kB/s eta 0:00:24
   ----------------------- ---------------- 14.2/24.4 MB 450.0 kB/s eta 0:00:23
   ----------------------- ---------------- 14.2/24.4 MB 450.0 kB/s eta 0:00:23
   ----------------------- ---------------- 14.2/24.4 MB 450.0 kB/s eta 0:00:23
   ----------------------- ---------------- 14.4/24.4 MB 448.9 kB/s eta 0:00:23
   ------------------------ --------------- 14.7/24.4 MB 454.5 kB/s eta 0:00:22
   ------------------------- -------------- 15.7/24.4 MB 488.1 kB/s eta 0:00:18
   -------------------------- ------------- 16.3/24.4 MB 504.6 kB/s eta 0:00:17
   --------------------------- ------------ 16.5/24.4 MB 510.5 kB/s eta 0:00:16
   --------------------------- ------------ 16.8/24.4 MB 515.1 kB/s eta 0:00:15
   --------------------------- ------------ 16.8/24.4 MB 515.1 kB/s eta 0:00:15
   --------------------------- ------------ 16.8/24.4 MB 515.1 kB/s eta 0:00:15
   --------------------------- ------------ 17.0/24.4 MB 516.2 kB/s eta 0:00:15
   --------------------------- ------------ 17.0/24.4 MB 516.2 kB/s eta 0:00:15
   --------------------------- ------------ 17.0/24.4 MB 516.2 kB/s eta 0:00:15
   --------------------------- ------------ 17.0/24.4 MB 516.2 kB/s eta 0:00:15
   ---------------------------- ----------- 17.3/24.4 MB 517.8 kB/s eta 0:00:14
   ---------------------------- ----------- 17.3/24.4 MB 517.8 kB/s eta 0:00:14
   ---------------------------- ----------- 17.3/24.4 MB 517.8 kB/s eta 0:00:14
   ---------------------------- ----------- 17.3/24.4 MB 517.8 kB/s eta 0:00:14
   ---------------------------- ----------- 17.6/24.4 MB 514.6 kB/s eta 0:00:14
   ---------------------------- ----------- 17.6/24.4 MB 514.6 kB/s eta 0:00:14
   ---------------------------- ----------- 17.6/24.4 MB 514.6 kB/s eta 0:00:14
   ----------------------------- ---------- 17.8/24.4 MB 517.4 kB/s eta 0:00:13
   ----------------------------- ---------- 18.1/24.4 MB 522.6 kB/s eta 0:00:13
   ------------------------------ --------- 18.4/24.4 MB 525.5 kB/s eta 0:00:12
   ------------------------------ --------- 18.6/24.4 MB 530.7 kB/s eta 0:00:11
   ------------------------------ --------- 18.9/24.4 MB 535.9 kB/s eta 0:00:11
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.1/24.4 MB 542.7 kB/s eta 0:00:10
   ------------------------------- -------- 19.4/24.4 MB 521.8 kB/s eta 0:00:10
   ------------------------------- -------- 19.4/24.4 MB 521.8 kB/s eta 0:00:10
   -------------------------------- ------- 19.7/24.4 MB 521.4 kB/s eta 0:00:10
   -------------------------------- ------- 19.7/24.4 MB 521.4 kB/s eta 0:00:10
   -------------------------------- ------- 19.9/24.4 MB 524.3 kB/s eta 0:00:09
   --------------------------------- ------ 20.2/24.4 MB 527.6 kB/s eta 0:00:08
   --------------------------------- ------ 20.2/24.4 MB 527.6 kB/s eta 0:00:08
   --------------------------------- ------ 20.2/24.4 MB 527.6 kB/s eta 0:00:08
   --------------------------------- ------ 20.2/24.4 MB 527.6 kB/s eta 0:00:08
   --------------------------------- ------ 20.2/24.4 MB 527.6 kB/s eta 0:00:08
   --------------------------------- ------ 20.4/24.4 MB 524.5 kB/s eta 0:00:08
   --------------------------------- ------ 20.7/24.4 MB 527.7 kB/s eta 0:00:07
   ---------------------------------- ----- 21.0/24.4 MB 533.0 kB/s eta 0:00:07
   ---------------------------------- ----- 21.2/24.4 MB 538.3 kB/s eta 0:00:06
   ----------------------------------- ---- 21.5/24.4 MB 542.9 kB/s eta 0:00:06
   ----------------------------------- ---- 21.8/24.4 MB 545.5 kB/s eta 0:00:05
   ------------------------------------ --- 22.3/24.4 MB 552.7 kB/s eta 0:00:04
   ------------------------------------ --- 22.5/24.4 MB 555.3 kB/s eta 0:00:04
   ------------------------------------- -- 22.8/24.4 MB 562.8 kB/s eta 0:00:03
   -------------------------------------- - 23.6/24.4 MB 578.9 kB/s eta 0:00:02
   ---------------------------------------  23.9/24.4 MB 586.9 kB/s eta 0:00:01
   ---------------------------------------  24.4/24.4 MB 594.4 kB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 587.1 kB/s eta 0:00:00
Downloading smart_open-7.6.0-py3-none-any.whl (64 kB)
Installing collected packages: smart_open, gensim

   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   -------------------- ------------------- 1/2 [gensim]
   ---------------------------------------- 2/2 [gensim]

Successfully installed gensim-4.4.0 smart_open-7.6.0

In [11]:

import gensim.downloader as api
import numpy as np

model=api.load("glove-wiki-gigaword-50")

def avg_embedding(text):
    words=text.lower().split()
    vectors=[model[w] for w in words if w in model]

    if len(vectors)==0:
        return np.zeros(50)

    return np.mean(vectors,axis=0)

vec=avg_embedding(df['statement'][0])

print("Taille du vecteur:", len(vec))
print(vec[:10])

[==================================================] 100.0% 66.0/66.0MB downloaded
Taille du vecteur: 50
[-0.14706667  0.56179667  0.24353667 -0.5806866   0.5555367  -0.8902003
  0.29507333  0.221344    0.04625333  0.79141736]


Chaque mot devient un vecteur mathématique.

Cette méthode comprend mieux les relations entre :

- sad
- depressed
- unhappy

## Comparaison Finale

In [12]:

comparison=pd.DataFrame({
    "Méthode":[
        "NLP Pipeline",
        "Bag of Words",
        "TF-IDF",
        "Word Embedding"
    ],

    "Niveau":[
        "Prétraitement",
        "Simple",
        "Très efficace",
        "Avancé"
    ],

    "Recommandation":[
        "Obligatoire",
        "Baseline",
        "Très recommandé",
        "Option avancée"
    ]
})

comparison

          Méthode         Niveau   Recommandation
0    NLP Pipeline  Prétraitement      Obligatoire
1    Bag of Words         Simple         Baseline
2          TF-IDF  Très efficace  Très recommandé
3  Word Embedding         Avancé   Option avancée


### Conclusion

Pour ton projet :

1. NLP Pipeline → obligatoire  
2. TF-IDF → meilleur point de départ  
3. Tester ensuite SVM / Logistic Regression  
4. Word Embedding si vous voulez aller plus loin